spring:
  datasource:
    url: jdbc:mysql://root:ZITx6ZfCmozM1njg2HE0@containers-us-west-33.railway.app:6653/railway
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog